apiVersion: v1
kind: Secret
metadata:
  name: registrysecret
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5yZWJyYWlubWUuY29tIjp7InVzZXJuYW1lIjoicHVsbC1jcmVkcyIsInBhc3N3b3JkIjoiZ2xwYXQtdm5wTF9pdjdXeGR6QjJRUXVLRUUiLCJlbWFpbCI6InRlc3RAbWFpTCIsImF1dGgiOiJjSFZzYkMxamNtVmtjenBuYkhCaGRDMTJibkJNWDJsMk4xZDRaSHBDTWxGUmRVdEZSUT09In19fQ==
