apiVersion: v1
kind: Secret
metadata:
  name: librespeed-secret 
  namespace: final 
type: Opaque 
data:
  DB_PASSWORD: cGFzc3dvcmQ= # base64 for 'password' 
  DB_USER: dXNlcg==
  DB_USERNAME: dXNlcg==
  
