apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: db
  labels:
    app: db
data:
  MYSQL_DATABASE: "librespeed"
  DB_TYPE: "mysql"
  DB_CONNECTION: "mysql"
  DB_HOSTNAME: "mysql"
  DB_PORT: "3306"
  DB_NAME: "librespeed" 
