apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
  labels:
    app: db
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= # base64 for 'password' 
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_USERNAME: dXNlcg==
  DB_USER: dXNlcg==
  MYSQL_USER: dXNlcg==
